# Generated by Django 4.0.3 on 2022-03-29 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_searching_vehicle_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='parkingSpots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=122)),
                ('vehicle_type', models.CharField(blank=True, max_length=122)),
                ('vehicle_no', models.CharField(blank=True, max_length=122)),
                ('row_no', models.SmallIntegerField()),
                ('pos_no', models.SmallIntegerField()),
                ('occupancy', models.SmallIntegerField()),
                ('in_time', models.TimeField(blank=True, verbose_name=datetime.time)),
            ],
        ),
        migrations.DeleteModel(
            name='searching',
        ),
    ]
