# Generated by Django 4.0.3 on 2022-03-29 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_parkingspots_delete_searching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspots',
            name='in_time',
            field=models.TimeField(verbose_name=datetime.time),
        ),
    ]
