# Generated by Django 4.0.3 on 2022-04-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_parkingspots_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspots',
            name='in_time',
            field=models.TimeField(verbose_name=1648885962.4559188),
        ),
    ]
