# Generated by Django 4.0.3 on 2022-04-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_parkingspots_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspots',
            name='in_epoch',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='parkingspots',
            name='in_time',
            field=models.TimeField(),
        ),
    ]
